# Generated by Django 3.2.9 on 2021-11-24 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.CharField(choices=[('personal', 'personal'), ('education personal', 'education personal'), ('other', 'other'), ('certificates', 'certificates')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('files', models.FileField(upload_to='post/pdfs/')),
                ('fields', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.catagory')),
            ],
        ),
    ]
