# Generated by Django 3.2.9 on 2021-11-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='fields',
            field=models.CharField(max_length=50),
        ),
    ]
